# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tzero/v1/pay/common.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tzero/v1/pay/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from tzero.v1.pay import validate_pb2 as tzero_dot_v1_dot_pay_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19tzero/v1/pay/common.proto\x12\x0ctzero.v1.pay\x1a\x1b\x62uf/validate/validate.proto\x1a\x1btzero/v1/pay/validate.proto\"U\n\x07\x44\x65\x63imal\x12\x1a\n\x08unscaled\x18\n \x01(\x03R\x08unscaled\x12.\n\x08\x65xponent\x18\x14 \x01(\x05\x42\x12\xbaH\x0f\x1a\r\x18\x08(\xf8\xff\xff\xff\xff\xff\xff\xff\xff\x01R\x08\x65xponent\"\xb6\x01\n\x12UsdtOnChainPayment\x12:\n\x05\x63hain\x18\n \x01(\x0e\x32\x18.tzero.v1.pay.BlockchainB\n\xbaH\x07\x82\x01\x04\x10\x01 \x00R\x05\x63hain\x12\x32\n\x10on_chain_tx_hash\x18\x14 \x01(\tB\t\xbaH\x06r\x04\x88\xb5\x18\x01R\ronChainTxHash\x12\x30\n\x0esender_address\x18\x1e \x01(\tB\t\xbaH\x06r\x04\x90\xb5\x18\x01R\rsenderAddress\"\xdb\x01\n\rDepositOption\x12:\n\x05\x63hain\x18\n \x01(\x0e\x32\x18.tzero.v1.pay.BlockchainB\n\xbaH\x07\x82\x01\x04\x10\x01 \x00R\x05\x63hain\x12\x32\n\x0f\x64\x65posit_address\x18\x14 \x01(\tB\t\xbaH\x06r\x04\x90\xb5\x18\x01R\x0e\x64\x65positAddress\x12(\n\x0bpayment_uri\x18\x1e \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\npaymentUri\x12\x30\n\x0etoken_contract\x18( \x01(\tB\t\xbaH\x06r\x04\x90\xb5\x18\x01R\rtokenContract\"\xc6\x01\n\x18OnChainSettlementDetails\x12\x32\n\x10on_chain_tx_hash\x18\n \x01(\tB\t\xbaH\x06r\x04\x88\xb5\x18\x01R\ronChainTxHash\x12:\n\x05\x63hain\x18\x14 \x01(\x0e\x32\x18.tzero.v1.pay.BlockchainB\n\xbaH\x07\x82\x01\x04\x10\x01 \x00R\x05\x63hain\x12:\n\x13\x64\x65stination_address\x18\x1e \x01(\tB\t\xbaH\x06r\x04\x90\xb5\x18\x01R\x12\x64\x65stinationAddress*e\n\nBlockchain\x12\x1a\n\x16\x42LOCKCHAIN_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x42LOCKCHAIN_TRON\x10\n\x12\x12\n\x0e\x42LOCKCHAIN_ETH\x10\x14\x12\x12\n\x0e\x42LOCKCHAIN_BSC\x10\x1e*\x89\x01\n\x10\x46undsDisposition\x12!\n\x1d\x46UNDS_DISPOSITION_UNSPECIFIED\x10\x00\x12(\n$FUNDS_DISPOSITION_RETURNED_TO_SENDER\x10\n\x12(\n$FUNDS_DISPOSITION_RETAINED_BY_ISSUER\x10\x14\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tzero.v1.pay.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECIMAL'].fields_by_name['exponent']._loaded_options = None
  _globals['_DECIMAL'].fields_by_name['exponent']._serialized_options = b'\272H\017\032\r\030\010(\370\377\377\377\377\377\377\377\377\001'
  _globals['_USDTONCHAINPAYMENT'].fields_by_name['chain']._loaded_options = None
  _globals['_USDTONCHAINPAYMENT'].fields_by_name['chain']._serialized_options = b'\272H\007\202\001\004\020\001 \000'
  _globals['_USDTONCHAINPAYMENT'].fields_by_name['on_chain_tx_hash']._loaded_options = None
  _globals['_USDTONCHAINPAYMENT'].fields_by_name['on_chain_tx_hash']._serialized_options = b'\272H\006r\004\210\265\030\001'
  _globals['_USDTONCHAINPAYMENT'].fields_by_name['sender_address']._loaded_options = None
  _globals['_USDTONCHAINPAYMENT'].fields_by_name['sender_address']._serialized_options = b'\272H\006r\004\220\265\030\001'
  _globals['_DEPOSITOPTION'].fields_by_name['chain']._loaded_options = None
  _globals['_DEPOSITOPTION'].fields_by_name['chain']._serialized_options = b'\272H\007\202\001\004\020\001 \000'
  _globals['_DEPOSITOPTION'].fields_by_name['deposit_address']._loaded_options = None
  _globals['_DEPOSITOPTION'].fields_by_name['deposit_address']._serialized_options = b'\272H\006r\004\220\265\030\001'
  _globals['_DEPOSITOPTION'].fields_by_name['payment_uri']._loaded_options = None
  _globals['_DEPOSITOPTION'].fields_by_name['payment_uri']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_DEPOSITOPTION'].fields_by_name['token_contract']._loaded_options = None
  _globals['_DEPOSITOPTION'].fields_by_name['token_contract']._serialized_options = b'\272H\006r\004\220\265\030\001'
  _globals['_ONCHAINSETTLEMENTDETAILS'].fields_by_name['on_chain_tx_hash']._loaded_options = None
  _globals['_ONCHAINSETTLEMENTDETAILS'].fields_by_name['on_chain_tx_hash']._serialized_options = b'\272H\006r\004\210\265\030\001'
  _globals['_ONCHAINSETTLEMENTDETAILS'].fields_by_name['chain']._loaded_options = None
  _globals['_ONCHAINSETTLEMENTDETAILS'].fields_by_name['chain']._serialized_options = b'\272H\007\202\001\004\020\001 \000'
  _globals['_ONCHAINSETTLEMENTDETAILS'].fields_by_name['destination_address']._loaded_options = None
  _globals['_ONCHAINSETTLEMENTDETAILS'].fields_by_name['destination_address']._serialized_options = b'\272H\006r\004\220\265\030\001'
  _globals['_BLOCKCHAIN']._serialized_start=796
  _globals['_BLOCKCHAIN']._serialized_end=897
  _globals['_FUNDSDISPOSITION']._serialized_start=900
  _globals['_FUNDSDISPOSITION']._serialized_end=1037
  _globals['_DECIMAL']._serialized_start=101
  _globals['_DECIMAL']._serialized_end=186
  _globals['_USDTONCHAINPAYMENT']._serialized_start=189
  _globals['_USDTONCHAINPAYMENT']._serialized_end=371
  _globals['_DEPOSITOPTION']._serialized_start=374
  _globals['_DEPOSITOPTION']._serialized_end=593
  _globals['_ONCHAINSETTLEMENTDETAILS']._serialized_start=596
  _globals['_ONCHAINSETTLEMENTDETAILS']._serialized_end=794
# @@protoc_insertion_point(module_scope)
