# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tzero/v1/pay/validate.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tzero/v1/pay/validate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btzero/v1/pay/validate.proto\x12\x0ctzero.v1.pay\x1a\x1b\x62uf/validate/validate.proto:\xbf\x01\n\rvalid_tx_hash\x12\x19.buf.validate.StringRules\x18\xd1\x86\x03 \x01(\x08\x42~\xc2H{\ny\n\x14string.valid_tx_hash\x1a\x61this.matches(\'^(0x)?[0-9a-fA-F]{64}$\') ? \'\' : \'must be 64 hex characters, optionally 0x-prefixed\'R\x0bvalidTxHash:\xa7\x01\n\rvalid_address\x12\x19.buf.validate.StringRules\x18\xd2\x86\x03 \x01(\x08\x42\x65\xc2Hb\n`\n\x14string.valid_address\x1aHthis.size() >= 34 && this.size() <= 42 ? \'\' : \'must be 34-42 characters\'R\x0cvalidAddress')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tzero.v1.pay.validate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['valid_tx_hash']._loaded_options = None
  _globals['valid_tx_hash']._serialized_options = b'\302H{\ny\n\024string.valid_tx_hash\032athis.matches(\'^(0x)?[0-9a-fA-F]{64}$\') ? \'\' : \'must be 64 hex characters, optionally 0x-prefixed\''
  _globals['valid_address']._loaded_options = None
  _globals['valid_address']._serialized_options = b'\302Hb\n`\n\024string.valid_address\032Hthis.size() >= 34 && this.size() <= 42 ? \'\' : \'must be 34-42 characters\''
# @@protoc_insertion_point(module_scope)
