# Generated from tzero/v1/pay/acquirer/acquirer.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .acquirer_pb2 import CreatePaymentIntentRequest, CreatePaymentIntentResponse, GetPaymentQuoteRequest, GetPaymentQuoteResponse, PaymentAuthorizedRequest, PaymentAuthorizedResponse, PaymentExpiredRequest, PaymentExpiredResponse, PaymentFailedRequest, PaymentFailedResponse, SettlementCompletedRequest, SettlementCompletedResponse, SettlementInitiatedRequest, SettlementInitiatedResponse, SettlementReceivedRequest, SettlementReceivedResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class AcquirerService(Protocol):
    """
    *
    t-0 endpoints the Acquirer calls to price a payment, open a payment intent, and
    confirm fiat receipt.
    """
    async def get_payment_quote(self, request: GetPaymentQuoteRequest, ctx: RequestContext[GetPaymentQuoteRequest, GetPaymentQuoteResponse], /) -> GetPaymentQuoteResponse:
        """
        * Prices an upcoming local-fiat payment from t-0's Order Book of standing LP quotes; fiat settlement mode only.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def create_payment_intent(self, request: CreatePaymentIntentRequest, ctx: RequestContext[CreatePaymentIntentRequest, CreatePaymentIntentResponse], /) -> CreatePaymentIntentResponse:
        """
        * Opens a payment intent; t-0 reserves deposit addresses with the Issuer inline and returns the payment instructions.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def settlement_received(self, request: SettlementReceivedRequest, ctx: RequestContext[SettlementReceivedRequest, SettlementReceivedResponse], /) -> SettlementReceivedResponse:
        """
        * Confirms that a fiat settlement landed in the Acquirer's bank account; fiat settlement mode only, and the only event that settles the covered intents.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class AcquirerServiceASGIApplication(ConnectASGIApplication[AcquirerService]):
    def __init__(
        self,
        service: AcquirerService | AsyncGenerator[AcquirerService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.pay.acquirer.AcquirerService/GetPaymentQuote": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPaymentQuote",
                        service_name="tzero.v1.pay.acquirer.AcquirerService",
                        input=GetPaymentQuoteRequest,
                        output=GetPaymentQuoteResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_payment_quote,
                ),
                "/tzero.v1.pay.acquirer.AcquirerService/CreatePaymentIntent": Endpoint.unary(
                    method=MethodInfo(
                        name="CreatePaymentIntent",
                        service_name="tzero.v1.pay.acquirer.AcquirerService",
                        input=CreatePaymentIntentRequest,
                        output=CreatePaymentIntentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.create_payment_intent,
                ),
                "/tzero.v1.pay.acquirer.AcquirerService/SettlementReceived": Endpoint.unary(
                    method=MethodInfo(
                        name="SettlementReceived",
                        service_name="tzero.v1.pay.acquirer.AcquirerService",
                        input=SettlementReceivedRequest,
                        output=SettlementReceivedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.settlement_received,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.acquirer.AcquirerService"


class AcquirerServiceClient(ConnectClient):
    """
    *
    t-0 endpoints the Acquirer calls to price a payment, open a payment intent, and
    confirm fiat receipt.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def get_payment_quote(
        self,
        request: GetPaymentQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetPaymentQuoteResponse:
        """
        * Prices an upcoming local-fiat payment from t-0's Order Book of standing LP quotes; fiat settlement mode only.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPaymentQuote",
                service_name="tzero.v1.pay.acquirer.AcquirerService",
                input=GetPaymentQuoteRequest,
                output=GetPaymentQuoteResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def create_payment_intent(
        self,
        request: CreatePaymentIntentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreatePaymentIntentResponse:
        """
        * Opens a payment intent; t-0 reserves deposit addresses with the Issuer inline and returns the payment instructions.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePaymentIntent",
                service_name="tzero.v1.pay.acquirer.AcquirerService",
                input=CreatePaymentIntentRequest,
                output=CreatePaymentIntentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def settlement_received(
        self,
        request: SettlementReceivedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SettlementReceivedResponse:
        """
        * Confirms that a fiat settlement landed in the Acquirer's bank account; fiat settlement mode only, and the only event that settles the covered intents.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SettlementReceived",
                service_name="tzero.v1.pay.acquirer.AcquirerService",
                input=SettlementReceivedRequest,
                output=SettlementReceivedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class AcquirerServiceSync(Protocol):
    """
    *
    t-0 endpoints the Acquirer calls to price a payment, open a payment intent, and
    confirm fiat receipt.
    """
    def get_payment_quote(self, request: GetPaymentQuoteRequest, ctx: RequestContext[GetPaymentQuoteRequest, GetPaymentQuoteResponse], /) -> GetPaymentQuoteResponse:
        """
        * Prices an upcoming local-fiat payment from t-0's Order Book of standing LP quotes; fiat settlement mode only.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def create_payment_intent(self, request: CreatePaymentIntentRequest, ctx: RequestContext[CreatePaymentIntentRequest, CreatePaymentIntentResponse], /) -> CreatePaymentIntentResponse:
        """
        * Opens a payment intent; t-0 reserves deposit addresses with the Issuer inline and returns the payment instructions.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def settlement_received(self, request: SettlementReceivedRequest, ctx: RequestContext[SettlementReceivedRequest, SettlementReceivedResponse], /) -> SettlementReceivedResponse:
        """
        * Confirms that a fiat settlement landed in the Acquirer's bank account; fiat settlement mode only, and the only event that settles the covered intents.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class AcquirerServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: AcquirerServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.pay.acquirer.AcquirerService/GetPaymentQuote": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPaymentQuote",
                        service_name="tzero.v1.pay.acquirer.AcquirerService",
                        input=GetPaymentQuoteRequest,
                        output=GetPaymentQuoteResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_payment_quote,
                ),
                "/tzero.v1.pay.acquirer.AcquirerService/CreatePaymentIntent": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreatePaymentIntent",
                        service_name="tzero.v1.pay.acquirer.AcquirerService",
                        input=CreatePaymentIntentRequest,
                        output=CreatePaymentIntentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.create_payment_intent,
                ),
                "/tzero.v1.pay.acquirer.AcquirerService/SettlementReceived": EndpointSync.unary(
                    method=MethodInfo(
                        name="SettlementReceived",
                        service_name="tzero.v1.pay.acquirer.AcquirerService",
                        input=SettlementReceivedRequest,
                        output=SettlementReceivedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.settlement_received,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.acquirer.AcquirerService"


class AcquirerServiceClientSync(ConnectClientSync):
    """
    *
    t-0 endpoints the Acquirer calls to price a payment, open a payment intent, and
    confirm fiat receipt.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def get_payment_quote(
        self,
        request: GetPaymentQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetPaymentQuoteResponse:
        """
        * Prices an upcoming local-fiat payment from t-0's Order Book of standing LP quotes; fiat settlement mode only.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPaymentQuote",
                service_name="tzero.v1.pay.acquirer.AcquirerService",
                input=GetPaymentQuoteRequest,
                output=GetPaymentQuoteResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def create_payment_intent(
        self,
        request: CreatePaymentIntentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreatePaymentIntentResponse:
        """
        * Opens a payment intent; t-0 reserves deposit addresses with the Issuer inline and returns the payment instructions.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePaymentIntent",
                service_name="tzero.v1.pay.acquirer.AcquirerService",
                input=CreatePaymentIntentRequest,
                output=CreatePaymentIntentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def settlement_received(
        self,
        request: SettlementReceivedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SettlementReceivedResponse:
        """
        * Confirms that a fiat settlement landed in the Acquirer's bank account; fiat settlement mode only, and the only event that settles the covered intents.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SettlementReceived",
                service_name="tzero.v1.pay.acquirer.AcquirerService",
                input=SettlementReceivedRequest,
                output=SettlementReceivedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
class AcquirerCallbackService(Protocol):
    """
    *
    Acquirer-implemented callbacks t-0 pushes: authorization, settlement
    progress, expiry, and payment failure. Each is delivered at least once; the
    Acquirer dedupes on the t-0-minted id it carries.
    """
    async def payment_authorized(self, request: PaymentAuthorizedRequest, ctx: RequestContext[PaymentAuthorizedRequest, PaymentAuthorizedResponse], /) -> PaymentAuthorizedResponse:
        """
        * Tells the merchant the payment is approved; from here the Issuer is obligated to settle.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def settlement_initiated(self, request: SettlementInitiatedRequest, ctx: RequestContext[SettlementInitiatedRequest, SettlementInitiatedResponse], /) -> SettlementInitiatedResponse:
        """
        * Pre-notice that the LP sent a fiat bank transfer, naming the reference to expect; fiat settlement mode only, and does not settle the intents.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def settlement_completed(self, request: SettlementCompletedRequest, ctx: RequestContext[SettlementCompletedRequest, SettlementCompletedResponse], /) -> SettlementCompletedResponse:
        """
        * The Issuer's USDt settlement verified on-chain as reaching the Acquirer's wallet, with the intents it clears; USDt settlement mode only — in fiat mode the Acquirer's own SettlementReceived is the terminal event.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def payment_expired(self, request: PaymentExpiredRequest, ctx: RequestContext[PaymentExpiredRequest, PaymentExpiredResponse], /) -> PaymentExpiredResponse:
        """
        * The QR window lapsed with no payment; clear the pending order and drop the QR.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def payment_failed(self, request: PaymentFailedRequest, ctx: RequestContext[PaymentFailedRequest, PaymentFailedResponse], /) -> PaymentFailedResponse:
        """
        * A deposit arrived that the Issuer will not process; the payment is over and will not settle.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class AcquirerCallbackServiceASGIApplication(ConnectASGIApplication[AcquirerCallbackService]):
    def __init__(
        self,
        service: AcquirerCallbackService | AsyncGenerator[AcquirerCallbackService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.pay.acquirer.AcquirerCallbackService/PaymentAuthorized": Endpoint.unary(
                    method=MethodInfo(
                        name="PaymentAuthorized",
                        service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                        input=PaymentAuthorizedRequest,
                        output=PaymentAuthorizedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.payment_authorized,
                ),
                "/tzero.v1.pay.acquirer.AcquirerCallbackService/SettlementInitiated": Endpoint.unary(
                    method=MethodInfo(
                        name="SettlementInitiated",
                        service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                        input=SettlementInitiatedRequest,
                        output=SettlementInitiatedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.settlement_initiated,
                ),
                "/tzero.v1.pay.acquirer.AcquirerCallbackService/SettlementCompleted": Endpoint.unary(
                    method=MethodInfo(
                        name="SettlementCompleted",
                        service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                        input=SettlementCompletedRequest,
                        output=SettlementCompletedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.settlement_completed,
                ),
                "/tzero.v1.pay.acquirer.AcquirerCallbackService/PaymentExpired": Endpoint.unary(
                    method=MethodInfo(
                        name="PaymentExpired",
                        service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                        input=PaymentExpiredRequest,
                        output=PaymentExpiredResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.payment_expired,
                ),
                "/tzero.v1.pay.acquirer.AcquirerCallbackService/PaymentFailed": Endpoint.unary(
                    method=MethodInfo(
                        name="PaymentFailed",
                        service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                        input=PaymentFailedRequest,
                        output=PaymentFailedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.payment_failed,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.acquirer.AcquirerCallbackService"


class AcquirerCallbackServiceClient(ConnectClient):
    """
    *
    Acquirer-implemented callbacks t-0 pushes: authorization, settlement
    progress, expiry, and payment failure. Each is delivered at least once; the
    Acquirer dedupes on the t-0-minted id it carries.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def payment_authorized(
        self,
        request: PaymentAuthorizedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PaymentAuthorizedResponse:
        """
        * Tells the merchant the payment is approved; from here the Issuer is obligated to settle.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PaymentAuthorized",
                service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                input=PaymentAuthorizedRequest,
                output=PaymentAuthorizedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def settlement_initiated(
        self,
        request: SettlementInitiatedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SettlementInitiatedResponse:
        """
        * Pre-notice that the LP sent a fiat bank transfer, naming the reference to expect; fiat settlement mode only, and does not settle the intents.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SettlementInitiated",
                service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                input=SettlementInitiatedRequest,
                output=SettlementInitiatedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def settlement_completed(
        self,
        request: SettlementCompletedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SettlementCompletedResponse:
        """
        * The Issuer's USDt settlement verified on-chain as reaching the Acquirer's wallet, with the intents it clears; USDt settlement mode only — in fiat mode the Acquirer's own SettlementReceived is the terminal event.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SettlementCompleted",
                service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                input=SettlementCompletedRequest,
                output=SettlementCompletedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def payment_expired(
        self,
        request: PaymentExpiredRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PaymentExpiredResponse:
        """
        * The QR window lapsed with no payment; clear the pending order and drop the QR.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PaymentExpired",
                service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                input=PaymentExpiredRequest,
                output=PaymentExpiredResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def payment_failed(
        self,
        request: PaymentFailedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PaymentFailedResponse:
        """
        * A deposit arrived that the Issuer will not process; the payment is over and will not settle.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PaymentFailed",
                service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                input=PaymentFailedRequest,
                output=PaymentFailedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class AcquirerCallbackServiceSync(Protocol):
    """
    *
    Acquirer-implemented callbacks t-0 pushes: authorization, settlement
    progress, expiry, and payment failure. Each is delivered at least once; the
    Acquirer dedupes on the t-0-minted id it carries.
    """
    def payment_authorized(self, request: PaymentAuthorizedRequest, ctx: RequestContext[PaymentAuthorizedRequest, PaymentAuthorizedResponse], /) -> PaymentAuthorizedResponse:
        """
        * Tells the merchant the payment is approved; from here the Issuer is obligated to settle.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def settlement_initiated(self, request: SettlementInitiatedRequest, ctx: RequestContext[SettlementInitiatedRequest, SettlementInitiatedResponse], /) -> SettlementInitiatedResponse:
        """
        * Pre-notice that the LP sent a fiat bank transfer, naming the reference to expect; fiat settlement mode only, and does not settle the intents.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def settlement_completed(self, request: SettlementCompletedRequest, ctx: RequestContext[SettlementCompletedRequest, SettlementCompletedResponse], /) -> SettlementCompletedResponse:
        """
        * The Issuer's USDt settlement verified on-chain as reaching the Acquirer's wallet, with the intents it clears; USDt settlement mode only — in fiat mode the Acquirer's own SettlementReceived is the terminal event.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def payment_expired(self, request: PaymentExpiredRequest, ctx: RequestContext[PaymentExpiredRequest, PaymentExpiredResponse], /) -> PaymentExpiredResponse:
        """
        * The QR window lapsed with no payment; clear the pending order and drop the QR.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def payment_failed(self, request: PaymentFailedRequest, ctx: RequestContext[PaymentFailedRequest, PaymentFailedResponse], /) -> PaymentFailedResponse:
        """
        * A deposit arrived that the Issuer will not process; the payment is over and will not settle.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class AcquirerCallbackServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: AcquirerCallbackServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.pay.acquirer.AcquirerCallbackService/PaymentAuthorized": EndpointSync.unary(
                    method=MethodInfo(
                        name="PaymentAuthorized",
                        service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                        input=PaymentAuthorizedRequest,
                        output=PaymentAuthorizedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.payment_authorized,
                ),
                "/tzero.v1.pay.acquirer.AcquirerCallbackService/SettlementInitiated": EndpointSync.unary(
                    method=MethodInfo(
                        name="SettlementInitiated",
                        service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                        input=SettlementInitiatedRequest,
                        output=SettlementInitiatedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.settlement_initiated,
                ),
                "/tzero.v1.pay.acquirer.AcquirerCallbackService/SettlementCompleted": EndpointSync.unary(
                    method=MethodInfo(
                        name="SettlementCompleted",
                        service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                        input=SettlementCompletedRequest,
                        output=SettlementCompletedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.settlement_completed,
                ),
                "/tzero.v1.pay.acquirer.AcquirerCallbackService/PaymentExpired": EndpointSync.unary(
                    method=MethodInfo(
                        name="PaymentExpired",
                        service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                        input=PaymentExpiredRequest,
                        output=PaymentExpiredResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.payment_expired,
                ),
                "/tzero.v1.pay.acquirer.AcquirerCallbackService/PaymentFailed": EndpointSync.unary(
                    method=MethodInfo(
                        name="PaymentFailed",
                        service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                        input=PaymentFailedRequest,
                        output=PaymentFailedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.payment_failed,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.acquirer.AcquirerCallbackService"


class AcquirerCallbackServiceClientSync(ConnectClientSync):
    """
    *
    Acquirer-implemented callbacks t-0 pushes: authorization, settlement
    progress, expiry, and payment failure. Each is delivered at least once; the
    Acquirer dedupes on the t-0-minted id it carries.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def payment_authorized(
        self,
        request: PaymentAuthorizedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PaymentAuthorizedResponse:
        """
        * Tells the merchant the payment is approved; from here the Issuer is obligated to settle.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PaymentAuthorized",
                service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                input=PaymentAuthorizedRequest,
                output=PaymentAuthorizedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def settlement_initiated(
        self,
        request: SettlementInitiatedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SettlementInitiatedResponse:
        """
        * Pre-notice that the LP sent a fiat bank transfer, naming the reference to expect; fiat settlement mode only, and does not settle the intents.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SettlementInitiated",
                service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                input=SettlementInitiatedRequest,
                output=SettlementInitiatedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def settlement_completed(
        self,
        request: SettlementCompletedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SettlementCompletedResponse:
        """
        * The Issuer's USDt settlement verified on-chain as reaching the Acquirer's wallet, with the intents it clears; USDt settlement mode only — in fiat mode the Acquirer's own SettlementReceived is the terminal event.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SettlementCompleted",
                service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                input=SettlementCompletedRequest,
                output=SettlementCompletedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def payment_expired(
        self,
        request: PaymentExpiredRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PaymentExpiredResponse:
        """
        * The QR window lapsed with no payment; clear the pending order and drop the QR.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PaymentExpired",
                service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                input=PaymentExpiredRequest,
                output=PaymentExpiredResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def payment_failed(
        self,
        request: PaymentFailedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PaymentFailedResponse:
        """
        * A deposit arrived that the Issuer will not process; the payment is over and will not settle.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PaymentFailed",
                service_name="tzero.v1.pay.acquirer.AcquirerCallbackService",
                input=PaymentFailedRequest,
                output=PaymentFailedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
