# Generated from tzero/v1/pay/issuer/issuer.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .issuer_pb2 import CreatePaymentInstructionsRequest, CreatePaymentInstructionsResponse, PaymentReceivedRequest, PaymentReceivedResponse, SettlementSentRequest, SettlementSentResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class IssuerService(Protocol):
    """
    *
    t-0 endpoints the Issuer calls to report what it did with a customer deposit
    and the USDt settlements that clear the intents it covers.
    """
    async def payment_received(self, request: PaymentReceivedRequest, ctx: RequestContext[PaymentReceivedRequest, PaymentReceivedResponse], /) -> PaymentReceivedResponse:
        """
        * Reports a deposit seen on-chain against an intent and the Issuer's final disposition of it.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def settlement_sent(self, request: SettlementSentRequest, ctx: RequestContext[SettlementSentRequest, SettlementSentResponse], /) -> SettlementSentResponse:
        """
        * Reports a USDt settlement sent on-chain to the registered destination, for t-0 to verify.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class IssuerServiceASGIApplication(ConnectASGIApplication[IssuerService]):
    def __init__(
        self,
        service: IssuerService | AsyncGenerator[IssuerService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.pay.issuer.IssuerService/PaymentReceived": Endpoint.unary(
                    method=MethodInfo(
                        name="PaymentReceived",
                        service_name="tzero.v1.pay.issuer.IssuerService",
                        input=PaymentReceivedRequest,
                        output=PaymentReceivedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.payment_received,
                ),
                "/tzero.v1.pay.issuer.IssuerService/SettlementSent": Endpoint.unary(
                    method=MethodInfo(
                        name="SettlementSent",
                        service_name="tzero.v1.pay.issuer.IssuerService",
                        input=SettlementSentRequest,
                        output=SettlementSentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.settlement_sent,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.issuer.IssuerService"


class IssuerServiceClient(ConnectClient):
    """
    *
    t-0 endpoints the Issuer calls to report what it did with a customer deposit
    and the USDt settlements that clear the intents it covers.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def payment_received(
        self,
        request: PaymentReceivedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PaymentReceivedResponse:
        """
        * Reports a deposit seen on-chain against an intent and the Issuer's final disposition of it.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PaymentReceived",
                service_name="tzero.v1.pay.issuer.IssuerService",
                input=PaymentReceivedRequest,
                output=PaymentReceivedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def settlement_sent(
        self,
        request: SettlementSentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SettlementSentResponse:
        """
        * Reports a USDt settlement sent on-chain to the registered destination, for t-0 to verify.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SettlementSent",
                service_name="tzero.v1.pay.issuer.IssuerService",
                input=SettlementSentRequest,
                output=SettlementSentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class IssuerServiceSync(Protocol):
    """
    *
    t-0 endpoints the Issuer calls to report what it did with a customer deposit
    and the USDt settlements that clear the intents it covers.
    """
    def payment_received(self, request: PaymentReceivedRequest, ctx: RequestContext[PaymentReceivedRequest, PaymentReceivedResponse], /) -> PaymentReceivedResponse:
        """
        * Reports a deposit seen on-chain against an intent and the Issuer's final disposition of it.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def settlement_sent(self, request: SettlementSentRequest, ctx: RequestContext[SettlementSentRequest, SettlementSentResponse], /) -> SettlementSentResponse:
        """
        * Reports a USDt settlement sent on-chain to the registered destination, for t-0 to verify.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class IssuerServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: IssuerServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.pay.issuer.IssuerService/PaymentReceived": EndpointSync.unary(
                    method=MethodInfo(
                        name="PaymentReceived",
                        service_name="tzero.v1.pay.issuer.IssuerService",
                        input=PaymentReceivedRequest,
                        output=PaymentReceivedResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.payment_received,
                ),
                "/tzero.v1.pay.issuer.IssuerService/SettlementSent": EndpointSync.unary(
                    method=MethodInfo(
                        name="SettlementSent",
                        service_name="tzero.v1.pay.issuer.IssuerService",
                        input=SettlementSentRequest,
                        output=SettlementSentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.settlement_sent,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.issuer.IssuerService"


class IssuerServiceClientSync(ConnectClientSync):
    """
    *
    t-0 endpoints the Issuer calls to report what it did with a customer deposit
    and the USDt settlements that clear the intents it covers.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def payment_received(
        self,
        request: PaymentReceivedRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PaymentReceivedResponse:
        """
        * Reports a deposit seen on-chain against an intent and the Issuer's final disposition of it.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PaymentReceived",
                service_name="tzero.v1.pay.issuer.IssuerService",
                input=PaymentReceivedRequest,
                output=PaymentReceivedResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def settlement_sent(
        self,
        request: SettlementSentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> SettlementSentResponse:
        """
        * Reports a USDt settlement sent on-chain to the registered destination, for t-0 to verify.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SettlementSent",
                service_name="tzero.v1.pay.issuer.IssuerService",
                input=SettlementSentRequest,
                output=SettlementSentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
class IssuerCallbackService(Protocol):
    """
    *
    Issuer-implemented endpoint t-0 calls to reserve deposit addresses and obtain
    the deposit options (chain-native payment URIs) for an intent.
    """
    async def create_payment_instructions(self, request: CreatePaymentInstructionsRequest, ctx: RequestContext[CreatePaymentInstructionsRequest, CreatePaymentInstructionsResponse], /) -> CreatePaymentInstructionsResponse:
        """
        * Reserves one deposit address per supported chain and returns the deposit options with their payment URIs.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class IssuerCallbackServiceASGIApplication(ConnectASGIApplication[IssuerCallbackService]):
    def __init__(
        self,
        service: IssuerCallbackService | AsyncGenerator[IssuerCallbackService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.pay.issuer.IssuerCallbackService/CreatePaymentInstructions": Endpoint.unary(
                    method=MethodInfo(
                        name="CreatePaymentInstructions",
                        service_name="tzero.v1.pay.issuer.IssuerCallbackService",
                        input=CreatePaymentInstructionsRequest,
                        output=CreatePaymentInstructionsResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.create_payment_instructions,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.issuer.IssuerCallbackService"


class IssuerCallbackServiceClient(ConnectClient):
    """
    *
    Issuer-implemented endpoint t-0 calls to reserve deposit addresses and obtain
    the deposit options (chain-native payment URIs) for an intent.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def create_payment_instructions(
        self,
        request: CreatePaymentInstructionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreatePaymentInstructionsResponse:
        """
        * Reserves one deposit address per supported chain and returns the deposit options with their payment URIs.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePaymentInstructions",
                service_name="tzero.v1.pay.issuer.IssuerCallbackService",
                input=CreatePaymentInstructionsRequest,
                output=CreatePaymentInstructionsResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class IssuerCallbackServiceSync(Protocol):
    """
    *
    Issuer-implemented endpoint t-0 calls to reserve deposit addresses and obtain
    the deposit options (chain-native payment URIs) for an intent.
    """
    def create_payment_instructions(self, request: CreatePaymentInstructionsRequest, ctx: RequestContext[CreatePaymentInstructionsRequest, CreatePaymentInstructionsResponse], /) -> CreatePaymentInstructionsResponse:
        """
        * Reserves one deposit address per supported chain and returns the deposit options with their payment URIs.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class IssuerCallbackServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: IssuerCallbackServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.pay.issuer.IssuerCallbackService/CreatePaymentInstructions": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreatePaymentInstructions",
                        service_name="tzero.v1.pay.issuer.IssuerCallbackService",
                        input=CreatePaymentInstructionsRequest,
                        output=CreatePaymentInstructionsResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.create_payment_instructions,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.issuer.IssuerCallbackService"


class IssuerCallbackServiceClientSync(ConnectClientSync):
    """
    *
    Issuer-implemented endpoint t-0 calls to reserve deposit addresses and obtain
    the deposit options (chain-native payment URIs) for an intent.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def create_payment_instructions(
        self,
        request: CreatePaymentInstructionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> CreatePaymentInstructionsResponse:
        """
        * Reserves one deposit address per supported chain and returns the deposit options with their payment URIs.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePaymentInstructions",
                service_name="tzero.v1.pay.issuer.IssuerCallbackService",
                input=CreatePaymentInstructionsRequest,
                output=CreatePaymentInstructionsResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
