# Generated from tzero/v1/pay/lp/lp.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .lp_pb2 import ExecuteQuoteRequest, ExecuteQuoteResponse, FiatSettlementSentRequest, FiatSettlementSentResponse, PublishQuoteRequest, PublishQuoteResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class LpService(Protocol):
    """
    *
    t-0 endpoints the LP calls to push standing quotes and to report its
    self-initiated fiat settlements. Fiat mode only.
    """
    async def publish_quote(self, request: PublishQuoteRequest, ctx: RequestContext[PublishQuoteRequest, PublishQuoteResponse], /) -> PublishQuoteResponse:
        """
        * Pushes immutable standing quotes into t-0's Order Book, at most one per currency per call; each is multi-consumable while it stands.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def fiat_settlement_sent(self, request: FiatSettlementSentRequest, ctx: RequestContext[FiatSettlementSentRequest, FiatSettlementSentResponse], /) -> FiatSettlementSentResponse:
        """
        *
        Reports a fiat bank-rails settlement the LP made on its own initiative against accepted quote executions.
        An execution still awaiting its durable result returns FAILED_PRECONDITION; retry the same request.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class LpServiceASGIApplication(ConnectASGIApplication[LpService]):
    def __init__(
        self,
        service: LpService | AsyncGenerator[LpService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.pay.lp.LpService/PublishQuote": Endpoint.unary(
                    method=MethodInfo(
                        name="PublishQuote",
                        service_name="tzero.v1.pay.lp.LpService",
                        input=PublishQuoteRequest,
                        output=PublishQuoteResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.publish_quote,
                ),
                "/tzero.v1.pay.lp.LpService/FiatSettlementSent": Endpoint.unary(
                    method=MethodInfo(
                        name="FiatSettlementSent",
                        service_name="tzero.v1.pay.lp.LpService",
                        input=FiatSettlementSentRequest,
                        output=FiatSettlementSentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.fiat_settlement_sent,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.lp.LpService"


class LpServiceClient(ConnectClient):
    """
    *
    t-0 endpoints the LP calls to push standing quotes and to report its
    self-initiated fiat settlements. Fiat mode only.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def publish_quote(
        self,
        request: PublishQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PublishQuoteResponse:
        """
        * Pushes immutable standing quotes into t-0's Order Book, at most one per currency per call; each is multi-consumable while it stands.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PublishQuote",
                service_name="tzero.v1.pay.lp.LpService",
                input=PublishQuoteRequest,
                output=PublishQuoteResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def fiat_settlement_sent(
        self,
        request: FiatSettlementSentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> FiatSettlementSentResponse:
        """
        *
        Reports a fiat bank-rails settlement the LP made on its own initiative against accepted quote executions.
        An execution still awaiting its durable result returns FAILED_PRECONDITION; retry the same request.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FiatSettlementSent",
                service_name="tzero.v1.pay.lp.LpService",
                input=FiatSettlementSentRequest,
                output=FiatSettlementSentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class LpServiceSync(Protocol):
    """
    *
    t-0 endpoints the LP calls to push standing quotes and to report its
    self-initiated fiat settlements. Fiat mode only.
    """
    def publish_quote(self, request: PublishQuoteRequest, ctx: RequestContext[PublishQuoteRequest, PublishQuoteResponse], /) -> PublishQuoteResponse:
        """
        * Pushes immutable standing quotes into t-0's Order Book, at most one per currency per call; each is multi-consumable while it stands.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def fiat_settlement_sent(self, request: FiatSettlementSentRequest, ctx: RequestContext[FiatSettlementSentRequest, FiatSettlementSentResponse], /) -> FiatSettlementSentResponse:
        """
        *
        Reports a fiat bank-rails settlement the LP made on its own initiative against accepted quote executions.
        An execution still awaiting its durable result returns FAILED_PRECONDITION; retry the same request.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class LpServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: LpServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.pay.lp.LpService/PublishQuote": EndpointSync.unary(
                    method=MethodInfo(
                        name="PublishQuote",
                        service_name="tzero.v1.pay.lp.LpService",
                        input=PublishQuoteRequest,
                        output=PublishQuoteResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.publish_quote,
                ),
                "/tzero.v1.pay.lp.LpService/FiatSettlementSent": EndpointSync.unary(
                    method=MethodInfo(
                        name="FiatSettlementSent",
                        service_name="tzero.v1.pay.lp.LpService",
                        input=FiatSettlementSentRequest,
                        output=FiatSettlementSentResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.fiat_settlement_sent,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.lp.LpService"


class LpServiceClientSync(ConnectClientSync):
    """
    *
    t-0 endpoints the LP calls to push standing quotes and to report its
    self-initiated fiat settlements. Fiat mode only.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def publish_quote(
        self,
        request: PublishQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PublishQuoteResponse:
        """
        * Pushes immutable standing quotes into t-0's Order Book, at most one per currency per call; each is multi-consumable while it stands.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PublishQuote",
                service_name="tzero.v1.pay.lp.LpService",
                input=PublishQuoteRequest,
                output=PublishQuoteResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def fiat_settlement_sent(
        self,
        request: FiatSettlementSentRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> FiatSettlementSentResponse:
        """
        *
        Reports a fiat bank-rails settlement the LP made on its own initiative against accepted quote executions.
        An execution still awaiting its durable result returns FAILED_PRECONDITION; retry the same request.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="FiatSettlementSent",
                service_name="tzero.v1.pay.lp.LpService",
                input=FiatSettlementSentRequest,
                output=FiatSettlementSentResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
class LpCallbackService(Protocol):
    """
    *
    LP-implemented endpoint t-0 calls to request the LP's durable decision on a
    standing quote execution for one authorized payment. Fiat mode only.
    """
    async def execute_quote(self, request: ExecuteQuoteRequest, ctx: RequestContext[ExecuteQuoteRequest, ExecuteQuoteResponse], /) -> ExecuteQuoteResponse:
        """
        * Requests a durable Accepted or Rejected result; only Accepted creates the LP's firm per-payment obligation.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class LpCallbackServiceASGIApplication(ConnectASGIApplication[LpCallbackService]):
    def __init__(
        self,
        service: LpCallbackService | AsyncGenerator[LpCallbackService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/tzero.v1.pay.lp.LpCallbackService/ExecuteQuote": Endpoint.unary(
                    method=MethodInfo(
                        name="ExecuteQuote",
                        service_name="tzero.v1.pay.lp.LpCallbackService",
                        input=ExecuteQuoteRequest,
                        output=ExecuteQuoteResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.execute_quote,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.lp.LpCallbackService"


class LpCallbackServiceClient(ConnectClient):
    """
    *
    LP-implemented endpoint t-0 calls to request the LP's durable decision on a
    standing quote execution for one authorized payment. Fiat mode only.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def execute_quote(
        self,
        request: ExecuteQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ExecuteQuoteResponse:
        """
        * Requests a durable Accepted or Rejected result; only Accepted creates the LP's firm per-payment obligation.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteQuote",
                service_name="tzero.v1.pay.lp.LpCallbackService",
                input=ExecuteQuoteRequest,
                output=ExecuteQuoteResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class LpCallbackServiceSync(Protocol):
    """
    *
    LP-implemented endpoint t-0 calls to request the LP's durable decision on a
    standing quote execution for one authorized payment. Fiat mode only.
    """
    def execute_quote(self, request: ExecuteQuoteRequest, ctx: RequestContext[ExecuteQuoteRequest, ExecuteQuoteResponse], /) -> ExecuteQuoteResponse:
        """
        * Requests a durable Accepted or Rejected result; only Accepted creates the LP's firm per-payment obligation.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class LpCallbackServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: LpCallbackServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/tzero.v1.pay.lp.LpCallbackService/ExecuteQuote": EndpointSync.unary(
                    method=MethodInfo(
                        name="ExecuteQuote",
                        service_name="tzero.v1.pay.lp.LpCallbackService",
                        input=ExecuteQuoteRequest,
                        output=ExecuteQuoteResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.execute_quote,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/tzero.v1.pay.lp.LpCallbackService"


class LpCallbackServiceClientSync(ConnectClientSync):
    """
    *
    LP-implemented endpoint t-0 calls to request the LP's durable decision on a
    standing quote execution for one authorized payment. Fiat mode only.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def execute_quote(
        self,
        request: ExecuteQuoteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> ExecuteQuoteResponse:
        """
        * Requests a durable Accepted or Rejected result; only Accepted creates the LP's firm per-payment obligation.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteQuote",
                service_name="tzero.v1.pay.lp.LpCallbackService",
                input=ExecuteQuoteRequest,
                output=ExecuteQuoteResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
