name: CI / Go

on:
  push:
    branches: [master]
    paths:
      - "cli/**"
      - "java/starter/**"
      - "node/starter/**"
      - "proto/**"
      - ".github/workflows/ci-go.yaml"
  pull_request:
    branches: [master]
    paths:
      - "cli/**"
      - "java/starter/**"
      - "node/starter/**"
      - "proto/**"
      - ".github/workflows/ci-go.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          show-progress: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: cli/go.mod

      - name: Generate templates
        working-directory: cli
        run: go generate ./...

      - name: Build
        working-directory: cli
        run: go build ./...

      - name: Test
        working-directory: cli
        run: go test ./...
