name: CI / Java

on:
  push:
    branches: [master]
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/ci-java.yaml"
  pull_request:
    branches: [master]
    paths:
      - "java/**"
      - "proto/**"
      - ".github/workflows/ci-java.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  java:
    name: Java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          show-progress: false

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Build
        working-directory: java
        run: ./gradlew build --no-daemon
